apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: ebs-static
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: ebs-static
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: persistent-storage
      mountPath: /usr/share/nginx/html
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1f
    
  volumes: 
   - name: persistent-storage
     persistentVolumeClaim:
       claimName: ebs-static
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
spec: 
  type: LoadBalancer
  selector: #labels arre used as selectors
    project: expense
    component: backend
    environment: dev
    version: "1.0.0"
    demo: lb
  ports:
  - protocol: TCP
    port: 80 #service port
    targetPort: 80 #container port number
    nodePort: 30007       
