apiVersion: v1
kind: Pod
metadata:
  name: labels
  annotations: 
  labels:
      buildURL: "https://jenkins.com/expense/job/backend/23"
      component: backend
      environment: dev
spec:
  containers:
  - name: nginx
    image: nginx