apiVersion: v1
kind: Pod
metadata:
  name: env
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
    # soft limit
     requests:
      memory: "68Mi"
      cpu: "100m"
    # hard limit
     limits:
     #limit can be equal to requests but not less than requests

      memory: "128Mi"
      cpu: "150m"